### ISSUE TITLE
Use relative heights

### ISSUE THREAD

**Issue by TheSharpieOne** [buildo/react-placeholder#10]
It would be very nice to have the height of the placeholder be based on the height of the text that would be there; inheriting from the parent.
This should probably be easily achieved using `em`s instead of `px`

This is useful for placeholding headers without having to manually set the height. (Note: manually setting the height on the default type (`'text'`) doesn't affect each row, only the height of the area as a whole)

**Comment by FrancescoCioria** [comment]
Hi @TheSharpieOne I agree with you, it's a good idea!
I think we can change the defaults to the equivalent in `em` based on a standard `font-size` of `14px`.
I'll open a PR shortly with these changes
