### ISSUE TITLE
Final element depends on the value of prop `ready`

### ISSUE THREAD

**Issue by kitce** [buildo/react-placeholder#45]
```
<ReactPlaceholder  ready={!!object}>
  <SomeComponent prop={object.someKey}/>
</ReactPlaceholder>
```

When I try to render to above element, I got `ReferenceError: object is not defined`.

I think it is because the behaviour of JSX, `children` will be rendered no matter `ready` is true or false.

Any suggestion on this case?

**Comment by FrancescoCioria** [comment]
Hi @kitce
The `ReferenceError` object represents an error when a non-existent variable is referenced. (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError)

This means that your variable `object` does not exist. It shouldn't be an issue related with `react-placeholder`.

If before your example you add `var object = true` the error should go away.

**Comment by gabro** [comment]
Hi @kitce, as @FrancescoCioria said this is has nothing specific to this component. However you can do something like:
 
```js
<ReactPlaceholder  ready={!!object}>
  {!!object && <SomeComponent prop={object.someKey} />}
</ReactPlaceholder>
```

`SomeComponent` will now be rendered only when `object` exists.

You can also factor this out as

```js
const read = !!object;
return (
  <ReactPlaceholder  ready={ready}>
    {ready && <SomeComponent prop={object.someKey} />}
  </ReactPlaceholder>
);
```
