### ISSUE TITLE
React 16 warning message

### ISSUE THREAD

**Issue by andrewkamphuis** [buildo/react-placeholder#46]
I'm not seeing any issues, but I'm getting the current warning of react-placeholder@1.0.6 requires a peer of react-dom@^0.14 || ^15 when running react-placeholder with React 16.

**Comment by FrancescoCioria** [comment]
right, we should update the `peerDependencies` in the `package.json` 👍

**Comment by gabro** [comment]
Closed by #48 and published as 1.0.7
