### ISSUE TITLE
Bug with delay when the component is already mounted

### ISSUE THREAD

**Issue by fabiopaiva-innovactory** [buildo/react-placeholder#54]
If you set a delay and the component is already mounted, when you set `ready` to `false`, it will use the same delay to start showing the placeholder. I want to start showing the placeholder immediately after setting `ready` to false.

I believe don't need to check the delay to set the `state` `ready` to `false` here:
https://github.com/buildo/react-placeholder/blob/master/src/ReactPlaceholder.js#L63

Am I wrong?

**Comment by fabiopaiva-innovactory** [comment]
It seems to be a misunderstanding, I thought the delay was to keep the placeholder for a while, to avoid the blinking content with fast connections. By the way, the delay is to wait some time to show the placeholder, anyway I can't see a use case for that.

**Comment by gabro** [comment]
It's exactly the opposite solution to the same problem :)

The `delay` delays the appearance of the placeholder in case of a fast connection. This way if your content loads fast you can skip the placeholder altogether and avoid the blinking.
