### ISSUE TITLE
install question

### ISSUE THREAD

**Issue by bluetch** [buildo/react-placeholder#58]
Excuse me, I would like to try this function, but got this warning, how could I go next?

<img width="882" alt="screenshot 2017-11-22 15 53 03" src="https://user-images.githubusercontent.com/4100698/33116063-3f12091c-cf9e-11e7-8200-f0f0403e5c91.png">

**Comment by FrancescoCioria** [comment]
Hi @bluetch,

In your image only the last two warnings are related to `react-placeholder`.
To solve them, you should install `react` and `react-dom` in your project as they are *required* but not installed by `react-placeholder`.

so, if they are missing from your `package.json` => add them and then run `npm install`
if they already exist in you `package.json` => simply run `npm install`

**Comment by bluetch** [comment]
thank you explain in detail, it works now :)
