### ISSUE TITLE
Typescript prop definition

### ISSUE THREAD

**Issue by KenavR** [buildo/react-placeholder#60]
I am not sure how the .d.ts file gets generated, otherwise, I would have added a PR, but currently, it defines the `delay` property to be required.

```typescript
interface ReactPlaceholderProps {
  // FIXME: children is marked as optional because of 
  // https://github.com/Microsoft/TypeScript/issues/8588
  children?: ReactChild,
  ready: boolean,
  delay: number,
  firstLaunchOnly?: boolean,
  type?: 'text' |  'media' | 'textRow' | 'rect' | 'round',
  rows?: number,
  color?: string,
  showLoadingAnimation?: boolean,
  customPlaceholder?: ReactNode | ReactElement<any>
}
```

A "?" behind the `delay` property should fix that. Otherwise great work.

**Comment by FrancescoCioria** [comment]
> I am not sure how the .d.ts file gets generated

currently... it's updated manually 😝 

yes, we should fix it.
I'll open a PR

**Comment by FrancescoCioria** [comment]
wait, it has already been fixed by https://github.com/buildo/react-placeholder/pull/53

I'll release a new version with the fix
