### ISSUE TITLE
Array.apply not support ie8 in TextBlock even if I'm add the polyfill

### ISSUE THREAD

**Issue by guxingke201** [buildo/react-placeholder#62]
![image](https://user-images.githubusercontent.com/8326941/34024724-b92199b2-e186-11e7-934c-074c1ff0f805.png)
could you change it to Array.from?

**Comment by FrancescoCioria** [comment]
ie8? seriously? not even Microsoft supports ie8 anymore 😝 

Anyway, to answer to your two questions:
1. I'm sorry, but I don't think we should change the code to support a 10years old browser that is no longer officially supported by anyone. If you really need to support IE8, I suggest you polyfill `Array.apply` directly on your project
2. `Array.from` is [muuuch more recent](https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Array/from) than `Array.apply` and is not even supported by IE11 => so I guess you're already using polyfills? In this case, adding the polyfill for `Array.apply` should not be a problem then :)

**Comment by guxingke201** [comment]
I'm already try to  use `es3ify-loader` and `babel-polyfill` to polyfill `Array.apply`,but failed. fortunately the `Array.from` success

**Comment by FrancescoCioria** [comment]
Ok, `Array.apply` is actually supported by IE8, but for some reason in IE8 it has a different API...

We could take advantage of ES6 by doing it as `[...Array(5)]` and let `babel` do their job

**Comment by FrancescoCioria** [comment]
published a fix in `1.0.10`

**Comment by guxingke201** [comment]
I'm sorry to say that your another solution failed...

**Comment by guxingke201** [comment]
In addition if we don't use babel ,the problem will not just `Array.from`

**Comment by guxingke201** [comment]
if you don't want `Array.from`, you could replace `range.map` by `for `

**Comment by FrancescoCioria** [comment]
That's weird, I tested it on IE10 and it looked to me that it correctly initialized an array without errors.
What error are you getting? Can you write it here?

**Comment by guxingke201** [comment]
There is no exception,just the `range.map` failed to traverse in ie8,I don't know why

**Comment by FrancescoCioria** [comment]
@guxingke201 I'm sorry, but if that didn't work I'm out of options: I'm not going to write bad code to support IE8.

I'm very pleased that you appreciate `react-placeholder` and wish to use it in your app, but I can't refactor code from ES6 to ES3 to support a browser that is no longer neither by Microsoft [nor by React](https://reactjs.org/blog/2016/01/12/discontinuing-ie8-support.html). I hope you will understand.

PS: to be honest, `react-placeholder` never even supported IE < 11 as it deeply uses `flexbox` for its layout :)

PPS: you should still be able to pass a custom placeholder, compatible with IE8, as `children`. You can look at [this example](http://buildo.github.io/react-placeholder/#!/ReactPlaceholder/11) for more information.
