### ISSUE TITLE
Do `children` and `ready` really have to be required props?

### ISSUE THREAD

**Issue by alanbuchanan** [buildo/react-placeholder#79]
For my use case, I am using this (awesome) component for purposes that don't relate to content loading: https://codesandbox.io/s/zz6o1ok56l

I am using this component in a small example project. I just have the component sitting there. It works perfectly well and does what I want. But I get console errors because I'm not passing `children` or the `ready` prop.

What does the author think of the above props being made optional?

**Comment by BrianMitchL** [comment]
v4 doesn't include prop-types checking anymore, with types being specified with TypeScript. It looks like your example runs fine with no console errors when using the latest react/react-dom and react-placeholder versions.
